// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyunloaeqseqgfbvjzob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5dW5sb2FlcXNlcWdmYnZqem9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTYxNjAsImV4cCI6MjA1OTQzMjE2MH0.4yTl8IIqj8_rujwLs5BOVbsXiYTFNPlWy6Ye5LdNSvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);